import React from "react";
import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from "@react-pdf/renderer";
import type { SharedReportPayload } from "@/lib/reports-shared";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10 },
  title: { fontSize: 18, marginBottom: 4 },
  subtitle: { fontSize: 9, color: "#666", marginBottom: 24 },
  sectionTitle: { fontSize: 12, marginBottom: 8 },
  block: { marginBottom: 16 },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 140 },
  value: {},
  list: { marginLeft: 8, marginTop: 4 },
});

export function ReportPdfDocument({ report }: { report: SharedReportPayload }) {
  const byTypeEntries = Object.entries(report.activity.byType)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 10);
  const byStatusEntries = Object.entries(report.activity.byStatus);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Mission Control – Report</Text>
        <Text style={styles.subtitle}>
          {report.startDate} – {report.endDate} · Generated{" "}
          {new Date(report.generatedAt).toLocaleString()}
        </Text>

        <View style={styles.block}>
          <Text style={styles.sectionTitle}>Activity summary</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Total activities:</Text>
            <Text style={styles.value}>{report.activity.total.toLocaleString()}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Success rate:</Text>
            <Text style={styles.value}>{report.activity.successRate}%</Text>
          </View>
          {byStatusEntries.length > 0 && (
            <View style={styles.list}>
              <Text>By status:</Text>
              {byStatusEntries.map(([status, count]) => (
                <Text key={status}>
                  {status}: {count.toLocaleString()}
                </Text>
              ))}
            </View>
          )}
          {byTypeEntries.length > 0 && (
            <View style={styles.list}>
              <Text>Top types:</Text>
              {byTypeEntries.map(([type, count]) => (
                <Text key={type}>
                  {type}: {count.toLocaleString()}
                </Text>
              ))}
            </View>
          )}
        </View>

        <View style={styles.block}>
          <Text style={styles.sectionTitle}>Cost summary</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Total cost:</Text>
            <Text style={styles.value}>${report.cost.total.toFixed(2)}</Text>
          </View>
          {report.cost.byModel.length > 0 && (
            <View style={styles.list}>
              <Text>By model:</Text>
              {report.cost.byModel.map((m) => (
                <Text key={m.model}>
                  {m.model}: ${m.cost.toFixed(2)} ({m.percentOfTotal}%)
                </Text>
              ))}
            </View>
          )}
        </View>

        <Text style={styles.subtitle}>Read-only shared report. Generated by Mission Control.</Text>
      </Page>
    </Document>
  );
}
